"""Add deposit payment models and fields

Revision ID: 171307fcf68e
Revises: d1fd298b8a89
Create Date: 2025-09-01 23:59:44.391788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '171307fcf68e'
down_revision = 'd1fd298b8a89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pagamento_sinal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_publico', sa.String(length=36), nullable=False),
    sa.Column('agendamento_id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['agendamento_id'], ['agendamento.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_publico')
    )
    with op.batch_alter_table('loja', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chave_pix', sa.String(length=200), nullable=True))

    with op.batch_alter_table('servico', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cobrar_sinal', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('percentual_sinal', sa.Numeric(precision=5, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servico', schema=None) as batch_op:
        batch_op.drop_column('percentual_sinal')
        batch_op.drop_column('cobrar_sinal')

    with op.batch_alter_table('loja', schema=None) as batch_op:
        batch_op.drop_column('chave_pix')

    op.drop_table('pagamento_sinal')
    # ### end Alembic commands ###
