"""Add auth and commission fields to models

Revision ID: d1fd298b8a89
Revises: 526e66c20f46
Create Date: 2025-09-01 23:39:27.025320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1fd298b8a89'
down_revision = '526e66c20f46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agendamento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('commission_paid', sa.Boolean(), nullable=False))

    with op.batch_alter_table('profissional', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('commission_percentage', sa.Numeric(precision=5, scale=2), nullable=False))
        batch_op.create_unique_constraint('uq_profissional_username', ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profissional', schema=None) as batch_op:
        batch_op.drop_constraint('uq_profissional_username', type_='unique')
        batch_op.drop_column('commission_percentage')
        batch_op.drop_column('password_hash')
        batch_op.drop_column('username')

    with op.batch_alter_table('agendamento', schema=None) as batch_op:
        batch_op.drop_column('commission_paid')

    # ### end Alembic commands ###
