"""Add phone to professional and webhook_url to store

Revision ID: d7d8a1067d6f
Revises: 171307fcf68e
Create Date: 2025-09-02 00:17:00.346814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7d8a1067d6f'
down_revision = '171307fcf68e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loja', schema=None) as batch_op:
        batch_op.add_column(sa.Column('webhook_url', sa.String(length=500), nullable=True))

    with op.batch_alter_table('profissional', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telefone', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profissional', schema=None) as batch_op:
        batch_op.drop_column('telefone')

    with op.batch_alter_table('loja', schema=None) as batch_op:
        batch_op.drop_column('webhook_url')

    # ### end Alembic commands ###
